// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCti4vc-mgpnpIQgxA2bX4y8bQWsAbBbWg',
    appId: '1:116907878347:web:a20199e2df961639de784e',
    messagingSenderId: '116907878347',
    projectId: 'coding-task-20a95',
    authDomain: 'coding-task-20a95.firebaseapp.com',
    storageBucket: 'coding-task-20a95.appspot.com',
    measurementId: 'G-XXNFJW5K8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNq6oI8_u5lBZSjWnxx8SdS-0qA6eC93I',
    appId: '1:116907878347:android:64081a41faafb6c3de784e',
    messagingSenderId: '116907878347',
    projectId: 'coding-task-20a95',
    storageBucket: 'coding-task-20a95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZASrXovUmONE2kZ2wNWdBNqMTyI9-rDc',
    appId: '1:116907878347:ios:bbf1b900efecde98de784e',
    messagingSenderId: '116907878347',
    projectId: 'coding-task-20a95',
    storageBucket: 'coding-task-20a95.appspot.com',
    iosBundleId: 'com.example.codingTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZASrXovUmONE2kZ2wNWdBNqMTyI9-rDc',
    appId: '1:116907878347:ios:bbf1b900efecde98de784e',
    messagingSenderId: '116907878347',
    projectId: 'coding-task-20a95',
    storageBucket: 'coding-task-20a95.appspot.com',
    iosBundleId: 'com.example.codingTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCti4vc-mgpnpIQgxA2bX4y8bQWsAbBbWg',
    appId: '1:116907878347:web:0f4c087aa81a4566de784e',
    messagingSenderId: '116907878347',
    projectId: 'coding-task-20a95',
    authDomain: 'coding-task-20a95.firebaseapp.com',
    storageBucket: 'coding-task-20a95.appspot.com',
    measurementId: 'G-5W1HK1DBMJ',
  );
}
